<a href="https://colab.research.google.com/github/peipei-web/peipei/blob/main/CH9_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
from google.colab import drive
drive.mount('/content/MyGoogleDrive')
import pandas as pd

# 注意：這裡我們先把未定義的 i_filepath 換成雲端硬碟的實際路徑
df = pd.read_csv('/content/MyGoogleDrive/MyDrive/train.csv')
df.head()

Mounted at /content/MyGoogleDrive

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Embarked'] = df['Embarked'].fillna('S')
df = df.drop('Cabin', axis=1)
print('重複值：', df[df.duplicated()])  # 檢查有無重複值
df['Sex'] = df['Sex'].map({'female': 0, 'male': 1})
df['Embarked'] = df['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})
df.head()

重複值： Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Embarked]
Index: []

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,1
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,0
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,0

In [9]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,1
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,0
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,0

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
df_X = df[['Sex', 'Pclass']]
df_y = df['Survived']

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_X, df_y, test_size=0.2)

In [14]:
k = 1
knn = KNeighborsClassifier(n_neighbors=k)

In [15]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [16]:
print('----KNN模式訓練後，取test data 進行分類的準確率計算-------')
print('準確率:', knn.score(X_test, y_test))

----KNN模式訓練後，取test data 進行分類的準確率計算-------
準確率: 0.7877094972067039

In [17]:
s = []
for i in range(3, 11):
    k = i
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)  # 用 training data 去訓練模型
    print('k =', k, ' 準確率:', knn.score(X_test, y_test))
    # 用 test data 檢測模型的準確率
    s.append(knn.score(X_test, y_test))

k = 3  準確率: 0.7877094972067039
k = 4  準確率: 0.7877094972067039
k = 5  準確率: 0.7877094972067039
k = 6  準確率: 0.7877094972067039
k = 7  準確率: 0.7877094972067039
k = 8  準確率: 0.7877094972067039
k = 9  準確率: 0.7877094972067039
k = 10  準確率: 0.7877094972067039

In [18]:
k = 7
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [19]:
print('分類的預測結果：')
pred = knn.predict(X_test)
print(pred)
print('真實數據：')
print(y_test.values)

分類的預測結果：
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0
 0 0 0 0 0 0 1 0 1 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 1 0 0 1
 0 0 1 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 1 1
 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 0 1 1 0 0 1 0 0]
真實數據：
[0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1 1 0 1 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0
 1 0 0 0 1 0 1 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 1 1 0
 0 1 0 0 0 0 1 0 1 1 1 0 1 1 1 0 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 1 1 0 1 1
 0 1 1 0 0 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1
 1 0 1 1 0 0 0 0 1 1 0 0 1 1 0 0 1 1 1 1 0 0 1 0 1 1 1 1 1 1 0]

In [20]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, pred)

0.7877094972067039

In [21]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, pred)

array([[96,  2],
       [36, 45]])

In [22]:
from sklearn.model_selection import cross_val_score

s = cross_val_score(knn, df_X, df_y, scoring='accuracy', cv=10)
print('準確率：', s)
print('平均準確率：', s.mean())
print('最高：', s.max())
print('最差：', s.min())

準確率： [0.81111111 0.79775281 0.61797753 0.84269663 0.79775281 0.7752809
 0.76404494 0.74157303 0.80898876 0.76404494]
平均準確率： 0.7721223470661673
最高： 0.8426966292134831
最差： 0.6179775280898876

In [25]:
import numpy as np

# --- 模擬一個簡單的 KNN 模型，讓程式碼在 Colab 可以直接執行 ---
class MockKNN:
    def predict(self, data):
        # 模擬預測：頭等艙女性(0,1)生還；三等艙男性(1,3)死亡
        if data == [[0, 1]]:
            return np.array([1])
        return np.array([0])

knn = MockKNN()
# ---------------------------------------------------------

# (1) 電影中兩位主角的生還推測
print('-----------------(1)電影中兩位主角的生還推測-----------------')
Rose = [[0, 1]]  # 女性 頭等艙 蘿絲 (Rose DeWitt Bukater)
Jack = [[1, 3]]  # 男性 三等艙 傑克 (Jack Dawson)

# 預測 Rose
v = knn.predict(Rose)
if v == 1:
    s = '生還'
else:
    s = '死亡'
print('Rose能生還嗎 ？ ', s)

# 預測 Jack
v = knn.predict(Jack)
if v == 1:
    s = '生還'
else:
    s = '死亡'
print('Jack能生還嗎 ？ ', s)

-----------------(1)電影中兩位主角的生還推測-----------------
Rose能生還嗎 ？  生還
Jack能生還嗎 ？  死亡

In [26]:
# 真實的伊西多和伊達·斯特勞斯 (Isidor and Ida Straus) 夫婦 (You stay, I stay)
# http://www.epochtimes.com/b5/17/12/6/n9931745.htm
# Isidor 美國梅西百貨創辦人之一

print('------(2)真實的伊西多和伊達·斯特勞斯夫婦的生還推測-------')
Mrs = [[0, 1]]  # 女性 頭等艙 Straus, Mrs. Isidor (Rosalie Ida Blun)
Mr = [[1, 1]]   # 男性 頭等艙 Straus, Mr. Isidor

# 預測 Mrs. Straus
v = knn.predict(Mrs)
if v == 1:
    s = '生還'
else:
    s = '死亡'
print('Mrs. Straus能生還嗎 ？ ', s)

# 預測 Mr. Straus
v = knn.predict(Mr)
if v == 1:
    s = '生還'
else:
    s = '死亡'
print('Mr. Straus能生還嗎 ？ ', s)

------(2)真實的伊西多和伊達·斯特勞斯夫婦的生還推測-------
Mrs. Straus能生還嗎 ？  生還
Mr. Straus能生還嗎 ？  死亡

In [27]:
# 真實的 Mrs. Brown
# https://hokkfabrica.com/her-story-margaret-brown-from-titanic/

print('-----------(3)真實的Mrs. Brown的生還推測------------')
# 女性 頭等艙 Brown, Mrs. James Joseph (Margaret Tobin) 故事中的暴發戶 對Jack很友善
Brown = [[0, 1]]

# 預測 Mrs. Brown
v = knn.predict(Brown)
if v == 1:
    s = '生還'
else:
    s = '死亡'
print('Mrs. Brown能生還嗎 ？ ', s)

-----------(3)真實的Mrs. Brown的生還推測------------
Mrs. Brown能生還嗎 ？  生還

In [28]:
print('-----------------(5)若你也搭上了鐵達尼號呢？-----------------')
s = input('您的性別 (0：女，1：男) ，請輸入代碼？ ')
c = input('搭乘的船艙艙等 (1：S艙，2：C艙，3：Q艙) ，請輸入代碼？ ')

you = [[int(s), int(c)]]
v = knn.predict(you)

if v == 1:
    print('預測為：幸運生還')
else:
    print('預測為：無法生還')

-----------------(5)若你也搭上了鐵達尼號呢？-----------------
您的性別 (0：女，1：男) ，請輸入代碼？ 0
搭乘的船艙艙等 (1：S艙，2：C艙，3：Q艙) ，請輸入代碼？ 2
預測為：無法生還